### ISSUE TITLE
export custom nodes

### ISSUE THREAD

**Issue by ksobon** [HydraShare/hydra-dynamo#5]
Given that Dynamo unlike Grasshopper doesn't inform you of what custom nodes are missing when you open the definition, it would be nice to include all of the custom nodes in Hydra export. How? The DYN file includes information about the custom node so that it can create a placeholder for it when such node is missing. What we can do is search the package folder that matches that information and just copy it to our directory before we zip them up all together. This won't solve the issue of a missing package when user opens the file, but at least it will allow them to copy such custom nodes to their package folder and open the sample file without any errors. 
Potential issues: Since dynamo 0.9.0 users can define their own custom location for custom packages so we would have to access that information somehow. I am not sure if that's possible yet. We will also be looking to search multiple tiers of folders and sub-folders as well as possibly having to look for DLLs. Some custom nodes might be part of a compiled package so there won't be a separate DYF file available but rather a single DLL. This could be an issue. What do you guys think?

**Comment by mostaphaRoudsari** [comment]
Hi @ksobon, This is a great --and very necessary-- idea. As we discussed offline IMO features like this are much better to be addressed in Dynamo level. Software like InDesign package the file for you and you can unpackage it later on any system. @tatlin and @kronz is there anything in this direction on Dynamo development list?

**Comment by ksobon** [comment]
It pretty much pertains to this request: 

https://github.com/DynamoDS/Dynamo/issues/4474

**Comment by kronz** [comment]
Hey,
So there are 2 different approaches referenced here, right? 
- zipping up all the custom nodes in a dyn file to travel with it so that a user can always open up a dyn file that is shared with them
- allowing users to quickly find and download custom nodes that are missing from a dyn file that is shared with them (this is what the other github issue is about).  

These are closely allied functionalities but very different approaches.  We are working on something pretty similar to the first right now, first going to show up on the Dynamo shared workspaces online, that will allow you to download a zipped file with Dyn and associated dyf files. But you are looking for something else too, an automatic load/install right?

**Comment by ksobon** [comment]
Yes, it would be nice to:
a. get a prompt when you open a file that has custom nodes from packages that are not installed on your machine. If that prompts gives me an option to install missing packages then its a slam dunk. If it only informs me of names/version of a missing packages then i can live with that. 
b. be able to "package" a file where not only a DYN definition gets saved but also all of the custom DYFs and/or DLLs that contain custom nodes. 

First approach is similar to what Grasshopper has while second is more like InDesign or Illustrator. I can live with either/or both. However, if its available via shared workspaces online and not for the stand alone users i don't think it will be quite useful. Of course i can change my mind if that functionality is exposed in some manageable manner via Dynamo API (when it arrives) so that we can re-create it for Hydra. 
The whole idea behind Hydra is to be able to share your workflows easier, so this would be a big step forward to sharing my workflows with others without attaching a list of packages that are required to actually use it. 

@kronz thanks for looking at this.

**Comment by mostaphaRoudsari** [comment]
> We are working on something pretty similar to the first right now, first going to show up on the Dynamo shared workspaces online, that will allow you to download a zipped file with Dyn and associated dyf files. But you are looking for something else too, an automatic load/install right?

@kronz yes but if you have the first option working then an automatic load/install will be a bonus. It's not as critical as having the file packaged in a .zip file.

@ksobon since Dynamo team is working on a very similar functionality I think we should just wait for them. Hydra for Grasshopper does export a list of dependencies which you can see at the bottom of the page. The user will know what are the plugins that she needs to open the file before even opening the file. Maybe we can implement a similar output while waiting for the new feature.

![image](https://cloud.githubusercontent.com/assets/2915573/11958152/24a385fc-a894-11e5-863c-f8222b5792ba.png)

cc: @alfarok

**Comment by ksobon** [comment]
@mostaphaRoudsari I agree

**Comment by alfarok** [comment]
Added a component dictionary for all the nodes on the canvas and the dependency list but for some reason its doesnt like the dependencies from the JSON.  When I go to the viewer nothing displays

![broken](https://cloud.githubusercontent.com/assets/13341935/12062418/3888cd8e-af6a-11e5-88e3-3152c3eb43d5.JPG)

When I remove the dependencies from the JSON it looks like this.

![nodes](https://cloud.githubusercontent.com/assets/13341935/12062440/9b417962-af6a-11e5-9927-08d843391e22.JPG)

I think it has something to do with how its generating that error message about updating the version of hydra. [This](https://raw.githubusercontent.com/alfarok/hydra/master/DynamoTest1/input.json) is what the JSON im producing looks like @mostaphaRoudsari

**Comment by mostaphaRoudsari** [comment]
@alfarok Nice! Are you following the latest [Hydra schema](https://github.com/HydraShare/hydra/wiki/Hydra-Schema-and-Folder-Structure#hydra-schema)?
Make sure you have **images** key and not **GHImg** and **RHImg** or whatever it used to be. If you have already following the updated schema, please copy the json file here I can be more helpful.

**Comment by alfarok** [comment]
@mostaphaRoudsari  Thanks, that was it!  Should be working as expected now.  I am going to uploaded a new package tomorrow with the recent additions and icons.
![working_tags](https://cloud.githubusercontent.com/assets/13341935/12068670/240b0d2e-afe0-11e5-8c2a-431a0c66ea8d.JPG)

**Comment by mostaphaRoudsari** [comment]
@alfarok good job! I'll try it in the coming week. I downloaded the other version but it never showed up in my Dynamo.

**Comment by alfarok** [comment]
@mostaphaRoudsari yeah sorry that is my fault the pkg.JSON isn't generating correctly I am working on fixing it now.  I was also thinking about changing the version numbers in the package manager to dates like "2016.01.01" because they don't let you delete old versions and just seems easier to manage.

**Comment by alfarok** [comment]
@mostaphaRoudsari  should be fixed if you download the latest version from the package manager 2016.1.4 ( should be 2016.1.1 but somehow i managed to change it to 4 so lets pretend this upload happened 3 days from now)

**Comment by mostaphaRoudsari** [comment]
@alfarok still doesn't show up for mine! Tested for sandbox and Revit.

![image](https://cloud.githubusercontent.com/assets/2915573/12217522/3b03f976-b6d1-11e5-81c9-992a0b004b48.png)

![image](https://cloud.githubusercontent.com/assets/2915573/12217532/94d91198-b6d1-11e5-8ada-1f46b397b43f.png)

Am I doing something wrong?

**Comment by alfarok** [comment]
@mostaphaRoudsari hmm, that's weird it seemed to work when i uploaded that last version.  What version of dynamo are you using?  I am out of town until tuesday but ill check it out when I get back.

**Comment by alfarok** [comment]
Also have you tried uninstalling the old version completely from the menu or appdata folder, restarting dynamo, and reinstalling?

**Comment by tatlin** [comment]
@mostaphaRoudsari what shows up in the Dynamo console in the ui or the log file on disk? There should be some diagnostic messages if a package or zero-touch lib can not be loaded.

**Comment by mostaphaRoudsari** [comment]
@alfarok I did remove it manually and tried again but it didn't help. @tatlin here is the error in the ui:

![image](https://cloud.githubusercontent.com/assets/2915573/12217985/5256ef1c-b6df-11e5-8bc5-d82e86fb68c8.png)

```
Exception when attempting to load package Hydra from C:\Users\Administrator\AppData\Roaming\Dynamo\0.9\packages\Hydra
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

**Comment by tatlin** [comment]
Usually that type of message is because a dependent dll can't be loaded. Are there any other dlls in the solution that need to be called by he zero touch dll? Also can be build config issues AnyCPU vs 64 bit

-matt

**Comment by alfarok** [comment]
Originally i changed the dynamo build version in the properties file to 9.0 from 8.2 which was causing the json to generate incorrectly.  Once i switched it back (even though i am using a 9.0 build) it worked for me again which is the latest version on the package manager.

**Comment by tatlin** [comment]
Are you both using 9.0 or a daily build?

**Comment by mostaphaRoudsari** [comment]
I'm using the daily build.

**Comment by alfarok** [comment]
I am using 9.0

**Comment by tatlin** [comment]
Mostapha try 9.0, there are namespace changes in the dailies right now 

-matt

**Comment by mostaphaRoudsari** [comment]
Ah! Ok. Thanks Matt.

@alfarok what do you think to rename the VS project from `SampleLibraryUI.customization` to `Hydra` at some point?

**Comment by alfarok** [comment]
@mostaphaRoudsari yes for sure, I am going to try and get a lot of little clean up done later this upcoming week.  There is still alot of unnecessary things we can delete that were included in the original sample folder along with renaming

**Comment by alfarok** [comment]
hey @mostaphaRoudsari, were you able to get the dynamo node to work?  Sorry I have been a little swamped lately with the start of a new semester.

**Comment by mostaphaRoudsari** [comment]
Hey @alfarok. I didn't go back to version 9.0 so it never showed up but it's not your fault. For now I did create Hydra's by editing your files. Also I added the video tag to the viewer page so you may want to include that in the node as an optional input.
http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Sunlighthours_Ladybug_Dynamo&slide=0&scale=1&offset=0,0

**Comment by alfarok** [comment]
@mostaphaRoudsari I finally got everything updated to 0.9.1.  I am hoping to work on adding additional image/video inputs and fixing the VS naming issues this week as well.

**Comment by alfarok** [comment]
Closing this old issue as we are successfully reading all dependencies and listing them from Dynamo to the web viewer as Mostapha states [here](https://github.com/HydraShare/hydra-dynamo/issues/5#issuecomment-166641641).  I can open a new enhancement issue for finding and including dyf files in the zipped folder.
